services:
  dev-hoge-backend-batch:
    image: dev-hoge-backend-batch:${GIT_BRANCH:-unknown}
    hostname: dev-hoge-backend-batch
    container_name: dev-hoge-backend-batch
    build:
      context: ../../../../
      dockerfile: ./hoge/docker/backend/batch/Dockerfile
      target: dev
      args:
        - ENVIRONMENT=dev
        - PROJECT=hoge
        - ROLE=backend
        - SERVICE=batch
        - GIT_BRANCH=${GIT_BRANCH:-unknown}
        - USER_NAME=${HOGE_USER_NAME:-hoge}
        - APP_DIR=${HOGE_APP_DIR:-app}
        - BACKEND_PROJECT=${HOGE_BACKEND_PROJECT:-backend}
        - PORT=8082
        - VSCODE_EXTENSION_JSON=extensions.json
    depends_on:
      dev-hoge-common-rust:
        condition: service_started
        required: false
      dev-hoge-backend-rdb:
        condition: service_healthy
        required: true
      dev-hoge-backend-rdb-replica:
        condition: service_healthy
        required: true
    restart: on-failure
    ports:
      - 8082:8082
    volumes:
      - type: bind
        source: ../../../${HOGE_APP_DIR:-app}
        target: /home/${HOGE_USER_NAME:-hoge}/${HOGE_APP_DIR:-app}
      - type: volume
        source: dev-hoge-backend-target-volume
        target: /home/${HOGE_USER_NAME:-hoge}/${HOGE_APP_DIR:-app}/${HOGE_BACKEND_PROJECT:-backend}/target
    init: true
    tty: true
    stdin_open: true
    networks:
      - dev-hoge-backend-network
    profiles:
      - dev
      - dev-hoge
      - dev-hoge-backend

networks:
  dev-hoge-backend-network:
    name: dev-hoge-backend-network

volumes:
  dev-hoge-backend-target-volume:
    name: dev-hoge-backend-target-volume
