apiVersion: v1
kind: Pod
metadata:
  name: my-image
spec:
  containers:
  - name: batch
    image: dev-hoge-backend-batch:prac-kind
    imagePullPolicy: Never
    command: ["/bin/sh", "-c", "while true; do sleep 1; done"]
