{%- set backends = ['batch', 'api', 'rdb', 'rdb-replica'] -%}
include:
  - ./docker/common/ubuntu/compose.yml
  - ./docker/common/proto/compose.yml
  {%- if has_frontend %}
  - ./docker/frontend/vite/compose.yml
  {%- endif %}
  {%- if has_backend %}
  - ./docker/backend/{{ backend }}/compose.yml
  {%- for backend in backends %}
  {%- endfor %}
  - ./docker/common/rust/compose.yml
  {%- endif %}
